### ISSUE TITLE
Not showing valid value after test_runner.sh

### ISSUE THREAD

**Issue by khyau** [moodlehq/moodle-performance-comparison#67]
Here is my issue, I had run this script for benchmark my moodle site.

However, I did not see any value in the result except latency.

$results[87][] = array(
    'thread'=>87,
    'starttime'=>1586339991470,
    **'dbreads'=>0,
    'dbwrites'=>0,
    'dbquerytime'=>0,
    'memoryused'=>'0',
    'filesincluded'=>'0',
    'serverload'=>'0',
    'sessionsize'=>'0',
    'timeused'=>'0',**
.........

all results value are zero.
What happened here?

Thanks

**Comment by stronk7** [comment]
Hi @khyau ,

in order to be possible to get all the indicators in the results... you need to enable some config setting in the site. Basically and, at very least, these:

https://github.com/moodlehq/moodle-performance-comparison/blob/016251e704e2ef0b790cec5cf00dbbd9ec68e3d4/config.php.template#L48-L54

Although it's always recommended to use that whole config.php.template file. Of course, NOT using you production database ever, but an empty one that the performance scripts will use to create the testing site.

With those settings... moodle will be printing the performance information on the footer of all pages and jmeter will capture it.

Hope it helps, ciao :-)

**Comment by khyau** [comment]
It works!!
Thanks @stronk7
